rpdr_seasons_data = [
    {
        "season": 1,
        "country": "US",
        "episode count": 7,
        "contestants": [
            {
                "name": "BeBe Zahara Benet",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 7,
            },
            {
                "name": "Nina Flowers",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 0,
                "episode count": 7,
            },
            {
                "name": "Rebecca Glasscock",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 7,
            },
            {
                "name": "Shannel",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 6,
            },
            {
                "name": "Ongina",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Jade",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Akashia",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 3,
            },
            {
                "name": "Tammie Brown",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            },
            {
                "name": "Victoria Porkchop Parker",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 2,
        "country": "US",
        "episode count": 10,
        "contestants": [
            {
                "name": "Tyra Sanchez",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 0,
                "episode count": 10,
            },
            {
                "name": "Raven",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 10,
            },
            {
                "name": "Jujubee",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 10,
            },
            {
                "name": "Tatianna",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 9,
            },
            {
                "name": "Pandora Boxx",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 8,
            },
            {
                "name": "Jessica Wild",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 7,
            },
            {
                "name": "Sahara Davenport",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 6,
            },
            {
                "name": "Morgan McMichaels",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 5,
            },
            {
                "name": "Sonique",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Mystique Summers Madison",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Nicole Paige Brooks",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            },
            {
                "name": "Shangela Laquifa Wadley",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 3,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Raja",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Manila Luzon",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Alexis Mateo",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 3,
                "episode count": 13,
            },
            {
                "name": "Yara Sofia",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 12,
            },
            {
                "name": "Carmen Carrera",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 11,
            },
            {
                "name": "Shangela",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 3,
                "episode count": 10,
            },
            {
                "name": "Delta Work",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 7,
            },
            {
                "name": "Stacy Layne Matthews",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 6,
            },
            {
                "name": "Mariah",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "India Ferrah",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 4,
            },
            {
                "name": "Mimi Imfurst",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Phoenix",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            },
            {
                "name": "Venus D-Lite",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 4,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Sharon Needles",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 4,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Chad Michaels",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Phi Phi O'Hara",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Latrice Royale",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 3,
                "episode count": 11,
            },
            {
                "name": "Kenya Michaels",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 6,
            },
            {
                "name": "DiDa Ritz",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 9,
            },
            {
                "name": "Willam",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 8,
            },
            {
                "name": "Jiggly Caliente",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 7,
            },
            {
                "name": "Milan",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 6,
            },
            {
                "name": "Madame LaQueer",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "The Princess",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 3,
            },
            {
                "name": "Lashauwn Beyond",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            },
            {
                "name": "Alisa Summers",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 5,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Jinkx Monsoon",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Alaska",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 0,
                "episode count": 13,
            },
            {
                "name": "Roxxxy Andrews",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Detox",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 11,
            },
            {
                "name": "Coco Montrese",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 4,
                "episode count": 10,
            },
            {
                "name": "Alyssa Edwards",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 9,
            },
            {
                "name": "Ivy Winters",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 8,
            },
            {
                "name": "Jade Jolie",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 6,
            },
            {
                "name": "Lineysha Sparx",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Honey Mahogany",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Vivienne Pinay",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Monica Beverly Hillz",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 3,
            },
            {
                "name": "Serena ChaCha",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 2,
            },
            {
                "name": "Penny Tration",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 6,
        "country": "US",
        "episode count": 12,
        "contestants": [
            {
                "name": "Bianca Del Rio",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 0,
                "episode count": 12,
            },
            {
                "name": "Adore Delano",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 2,
                "episode count": 12,
            },
            {
                "name": "Courtney Act",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 0,
                "episode count": 12,
            },
            {
                "name": "Darienne Lake",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 4,
                "episode count": 11,
            },
            {
                "name": "BenDeLaCreme",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 10,
            },
            {
                "name": "Joslyn Fox",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 9,
            },
            {
                "name": "Trinity K. Bonet",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 8,
            },
            {
                "name": "Laganja Estranja",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 7,
            },
            {
                "name": "Milk",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Gia Gunn",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "April Carrión",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 3,
            },
            {
                "name": "Vivacious",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 2,
            },
            {
                "name": "Magnolia Crawford",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            },
            {
                "name": "Kelly Mantle",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 7,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Violet Chachki",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 0,
                "episode count": 13,
            },
            {
                "name": "Ginger Minj",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 2,
                "episode count": 13,
            },
            {
                "name": "Pearl",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 13,
            },
            {
                "name": "Kennedy Davenport",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 3,
                "episode count": 12,
            },
            {
                "name": "Katya",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 11,
            },
            {
                "name": "Trixie Mattel",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 7,
            },
            {
                "name": "Miss Fame",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 9,
            },
            {
                "name": "Jaidynn Diore Fierce",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 8,
            },
            {
                "name": "Max",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 7,
            },
            {
                "name": "Kandy Ho",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 6,
            },
            {
                "name": "Mrs. Kasha Davis",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Jasmine Masters",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Sasha Belle",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            },
            {
                "name": "Tempest DuJour",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            },
        ]
    },
    {
        "season": 8,
        "country": "US",
        "episode count": 10,
        "contestants": [
            {
                "name": "Bob the Drag Queen",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 1,
                "episode count": 10,
            },
            {
                "name": "Kim Chi",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 0,
                "episode count": 10,
            },
            {
                "name": "Naomi Smalls",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 10,
            },
            {
                "name": "Chi Chi DeVayne",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 9,
            },
            {
                "name": "Derrick Barry",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 8,
            },
            {
                "name": "Thorgy Thor",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 7,
            },
            {
                "name": "Robbie Turner",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 6,
            },
            {
                "name": "Acid Betty",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Naysha Lopez",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 3,
            },
            {
                "name": "Cynthia Lee Fontaine",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Dax ExclamationPoint",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            },
            {
                "name": "Laila McQueen",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 2,
            }
        ]
    },
    {
        "season": 9,
        "country": "US",
        "episode count": 14,
        "contestants": [
            {
                "name": "Sasha Velour",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 0,
                "episode count": 14,
            },
            {
                "name": "Peppermint",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 14,
            },
            {
                "name": "Shea Couleé",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 4,
                "bottom two": 1,
                "episode count": 14,
            },
            {
                "name": "Trinity Taylor",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 1,
                "episode count": 14,
            },
            {
                "name": "Alexis Michelle",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 11,
            },
            {
                "name": "Nina Bo'nina Brown",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 10,
            },
            {
                "name": "Valentina",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 9,
            },
            {
                "name": "Farrah Moan",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 8,
            },
            {
                "name": "Aja",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 7,
            },
            {
                "name": "Cynthia Lee Fontaine",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 5,
            },
            {
                "name": "Eureka",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Charlie Hides",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Kimora Blac",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 3,
            },
            {
                "name": "Jaymes Mansfield",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            }
        ]
    },
    {
        "season": 10,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Aquaria",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 0,
                "episode count": 13,
            },
            {
                "name": "Eureka",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 13,
            },
            {
                "name": "Kameron Michaels",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 13,
            },
            {
                "name": "Asia O'Hara",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Miz Cracker",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 11,
            },
            {
                "name": "Monét X Change",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 10,
            },
            {
                "name": "The Vixen",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 8,
            },
            {
                "name": "Monique Heart",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 7,
            },
            {
                "name": "Blair St. Clair",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 6,
            },
            {
                "name": "Mayhem Miller",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 5,
            },
            {
                "name": "Dusty Ray Bottoms",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Yuhua Hamasaki",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Kalorie Karbdashian Williams",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 2,
            },
            {
                "name": "Vanessa Vanjie Mateo",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            },
        ]
    },
    {
        "season": 11,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Yvie Oddly",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Brooke Lynn Hytes",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 2,
                "episode count": 13,
            },
            {
                "name": "A'keria C. Davenport",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 13,
                "bottom two": 2,
                "episode count": 2,
            },
            {
                "name": "Silky Nutmeg Ganache",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 13,
            },
            {
                "name": "Vanessa Vanjie Mateo",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 12,
            },
            {
                "name": "Nina West",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 1,
                "episode count": 11,
            },
            {
                "name": "Shuga Cain",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 10,
            },
            {
                "name": "Plastique Tiara",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 9,
            },
            {
                "name": "Ra'Jah O'Hara",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 4,
                "episode count": 7,
            },
            {
                "name": "Scarlet Envy",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 6,
            },
            {
                "name": "Ariel Versace",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Mercedes Iman Diamond",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 4,
            },
            {
                "name": "Honey Davenport",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Kahanna Montrese",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 2,
            },
            {
                "name": "Soju",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 1,
            }
        ]
    },
    {
        "season": 12,
        "country": "US",
        "episode count": 12,
        "contestants": [
            {
                "name": "Jaida Essence Hall",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 1,
                "episode count": 12,
            },
            {
                "name": "Crystal Methyd",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 12,
            },
            {
                "name": "Gigi Goode",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 4,
                "bottom two": 0,
                "episode count": 12,
            },
            {
                "name": "Sherry Pie",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 0,
                "episode count": 11,
            },
            {
                "name": "Jackie Cox",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 11,
            },
            {
                "name": "Heidi N Closet",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 4,
                "episode count": 10,
            },
            {
                "name": "Widow Von'Du",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 8,
            },
            {
                "name": "Jan",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 7,
            },
            {
                "name": "Brita",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 3,
                "episode count": 6,
            },
            {
                "name": "Aiden Zhane",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 5,
            },
            {
                "name": "Nicky Doll",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 4,
            },
            {
                "name": "Rock M. Sakura",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Dahlia Sin",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            }
        ]
    },
    {
        "season":13,
        "country": "US",
        "episode count": 13,
        "contestants": [
            {
                "name": "Symone",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 4,
                "bottom two": 2,
                "episode count": 13,
            },
            {
                "name": "Kandy Muse",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 13,
            },
            {
                "name": "Gottmik",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 0,
                "episode count": 13,
            },
            {
                "name": "Rosé",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 0,
                "episode count": 13,
            },
            {
                "name": "Olivia Lux",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 11,
            },
            {
                "name": "Utica Queen",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 10,
            },
            {
                "name": "Tina Burner",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 9,
            },
            {
                "name": "Denali",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 8,
            },
            {
                "name": "Elliott with 2 Ts",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 7,
            },
            {
                "name": "LaLa Ri",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 5,
            },
            {
                "name": "Tamisha Iman",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Joey Jay",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "Kahmora Hall",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 2,
            }
        ]
    },
    {
        "season": 14,
        "country": "US",
        "episode count": 14,
        "contestants": [
            {
                "name": "Willow Pill",
                "won season": 1,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 14,
            },
            {
                "name": "Lady Camden",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 1,
                "episode count": 14,
            },
            {
                "name": "Angeria Paris VanMicheals",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 2,
                "bottom two": 2,
                "episode count": 14,
            },
            {
                "name": "Bosco",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 3,
                "bottom two": 2,
                "episode count": 14,
            },
            {
                "name": "Daya Betty",
                "won season": 0,
                "in finale": 1,
                "challenge wins": 1,
                "bottom two": 3,
                "episode count": 14,
            },
            {
                "name": "DeJa Skye",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 2,
                "episode count": 12,
            },
            {
                "name": "Jorgeous",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 5,
                "episode count": 12,
            },
            {
                "name": "Jasmine Kennedie",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 5,
                "episode count": 10,
            },
            {
                "name": "Kerri Colby",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 7,
            },
            {
                "name": "Maddy Morphosis",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 5,
            },
            {
                "name": "Orion Story",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 4,
            },
            {
                "name": "Kornbread 'The Snack' Jeté",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 1,
                "bottom two": 1,
                "episode count": 4,
            },
            {
                "name": "Alyssa Hunter",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 1,
                "episode count": 3,
            },
            {
                "name": "June Jambalaya",
                "won season": 0,
                "in finale": 0,
                "challenge wins": 0,
                "bottom two": 2,
                "episode count": 2,
            }
        ]
    }
]



